version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yourdbname
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
